Repository goormthon-Univ/2024_BEOTKKOTTHON_TEAM_31_BE, pull requests merged in 2024-03, with the labels that each got.

#3 feat: 임시 로그인 api 구현
  src/main/java/goorm/brainsnack/exception/BaseException.java
  src/main/java/goorm/brainsnack/exception/ErrorCode.java
  src/main/java/goorm/brainsnack/global/BaseResponse.java
  src/main/java/goorm/brainsnack/member/domain/Member.java
  src/main/java/goorm/brainsnack/member/dto/MemberResponseDto.java
  src/main/java/goorm/brainsnack/member/presentation/MemberController.java
  src/main/java/goorm/brainsnack/member/repository/MemberRepository.java
  src/main/java/goorm/brainsnack/member/service/MemberService.java
  src/main/java/goorm/brainsnack/member/service/MemberServiceImpl.java
Labels: enhancement

#4 Feat/main view api
  .github/PULL_REQUEST_TEMPLATE.md
  src/main/java/goorm/brainsnack/exception/ErrorCode.java
  src/main/java/goorm/brainsnack/member/domain/Member.java
  src/main/java/goorm/brainsnack/member/dto/MemberResponseDto.java
  src/main/java/goorm/brainsnack/member/presentation/MemberController.java
  src/main/java/goorm/brainsnack/member/service/MemberServiceImpl.java
  src/main/java/goorm/brainsnack/quiz/domain/MemberQuiz.java
  src/main/java/goorm/brainsnack/quiz/domain/Quiz.java
  src/main/java/goorm/brainsnack/quiz/domain/QuizData.java
  src/main/java/goorm/brainsnack/quiz/dto/QuizResponseDto.java
  src/main/java/goorm/brainsnack/quiz/presentation/QuizController.java
  src/main/java/goorm/brainsnack/quiz/repository/MemberQuizRepository.java
  src/main/java/goorm/brainsnack/quiz/repository/QuizRepository.java
  src/main/java/goorm/brainsnack/quiz/service/QuizService.java
  src/main/java/goorm/brainsnack/quiz/service/QuizServiceImpl.java
Labels: documentation, enhancement

#5 Feature/get category quiz list api
  src/main/java/goorm/brainsnack/exception/ErrorCode.java
  src/main/java/goorm/brainsnack/quiz/domain/QuizCategory.java
  src/main/java/goorm/brainsnack/quiz/dto/QuizResponseDto.java
  src/main/java/goorm/brainsnack/quiz/presentation/QuizController.java
  src/main/java/goorm/brainsnack/quiz/repository/QuizRepository.java
  src/main/java/goorm/brainsnack/quiz/service/QuizService.java
  src/main/java/goorm/brainsnack/quiz/service/QuizServiceImpl.java
Labels: enhancement

#8 Feature/quiz grade api
  src/main/java/goorm/brainsnack/exception/ErrorCode.java
  src/main/java/goorm/brainsnack/quiz/domain/MemberQuiz.java
  src/main/java/goorm/brainsnack/quiz/domain/QuizData.java
  src/main/java/goorm/brainsnack/quiz/dto/QuizRequestDto.java
  src/main/java/goorm/brainsnack/quiz/dto/QuizResponseDto.java
  src/main/java/goorm/brainsnack/quiz/presentation/QuizController.java
  src/main/java/goorm/brainsnack/quiz/repository/QuizDataRepository.java
  src/main/java/goorm/brainsnack/quiz/service/QuizService.java
  src/main/java/goorm/brainsnack/quiz/service/QuizServiceImpl.java
Labels: enhancement

#11 Feature/get result api
  src/main/java/goorm/brainsnack/exception/ErrorCode.java
  src/main/java/goorm/brainsnack/quiz/domain/MemberQuiz.java
  src/main/java/goorm/brainsnack/quiz/domain/Quiz.java
  src/main/java/goorm/brainsnack/quiz/domain/QuizData.java
  src/main/java/goorm/brainsnack/quiz/dto/QuizRequestDto.java
  src/main/java/goorm/brainsnack/quiz/dto/QuizResponseDto.java
  src/main/java/goorm/brainsnack/quiz/presentation/QuizController.java
  src/main/java/goorm/brainsnack/quiz/repository/MemberQuizRepository.java
  src/main/java/goorm/brainsnack/quiz/repository/QuizRepository.java
  src/main/java/goorm/brainsnack/quiz/service/QuizService.java
  src/main/java/goorm/brainsnack/quiz/service/QuizServiceImpl.java
Labels: bug, enhancement

#13 Fix/api error
  src/main/java/goorm/brainsnack/exception/ErrorCode.java
  src/main/java/goorm/brainsnack/global/config/WebConfig.java
  src/main/java/goorm/brainsnack/quiz/repository/MemberQuizRepository.java
  src/main/java/goorm/brainsnack/quiz/service/QuizServiceImpl.java
Labels: bug, enhancement

#16 SimilarQuiz API 수정
  src/main/java/goorm/brainsnack/member/domain/Member.java
  src/main/java/goorm/brainsnack/member/presentation/MemberController.java
  src/main/java/goorm/brainsnack/member/repository/MemberRepository.java
  src/main/java/goorm/brainsnack/member/service/MemberService.java
  src/main/java/goorm/brainsnack/member/service/MemberServiceImpl.java
  src/main/java/goorm/brainsnack/quiz/domain/MemberQuiz.java
  src/main/java/goorm/brainsnack/quiz/dto/QuizRequestDto.java
  src/main/java/goorm/brainsnack/quiz/dto/QuizResponseDto.java
  src/main/java/goorm/brainsnack/quiz/presentation/QuizController.java
  src/main/java/goorm/brainsnack/quiz/repository/MemberQuizRepository.java
  src/main/java/goorm/brainsnack/quiz/repository/QuizRepository.java
  src/main/java/goorm/brainsnack/quiz/service/ChatGPTServiceImpl.java
  src/main/java/goorm/brainsnack/quiz/service/QuizService.java
  src/main/java/goorm/brainsnack/quiz/service/QuizServiceImpl.java
Labels: bug

#19 Fix/error fix and code refactor
  src/main/java/goorm/brainsnack/exception/ErrorCode.java
  src/main/java/goorm/brainsnack/member/domain/Member.java
  src/main/java/goorm/brainsnack/member/dto/MemberResponseDto.java
  src/main/java/goorm/brainsnack/member/presentation/MemberController.java
  src/main/java/goorm/brainsnack/member/repository/MemberRepository.java
  src/main/java/goorm/brainsnack/member/service/MemberServiceImpl.java
  src/main/java/goorm/brainsnack/quiz/domain/MemberQuiz.java
  src/main/java/goorm/brainsnack/quiz/domain/Quiz.java
  src/main/java/goorm/brainsnack/quiz/domain/SimilarQuiz.java
  src/main/java/goorm/brainsnack/quiz/dto/QuizRequestDto.java
  src/main/java/goorm/brainsnack/quiz/dto/QuizResponseDto.java
  src/main/java/goorm/brainsnack/quiz/dto/SimilarQuizResponseDto.java
  src/main/java/goorm/brainsnack/quiz/init/QuizInit.java
  src/main/java/goorm/brainsnack/quiz/presentation/QuizController.java
  src/main/java/goorm/brainsnack/quiz/repository/MemberQuizRepository.java
  src/main/java/goorm/brainsnack/quiz/repository/QuizRepository.java
  src/main/java/goorm/brainsnack/quiz/repository/SimilarQuizRepository.java
  src/main/java/goorm/brainsnack/quiz/service/ChatGPTServiceImpl.java
  src/main/java/goorm/brainsnack/quiz/service/QuizService.java
  src/main/java/goorm/brainsnack/quiz/service/QuizServiceImpl.java
Labels: bug, enhancement

#21 Fix/create similar quiz refactor
  build.gradle
  src/main/java/goorm/brainsnack/global/config/S3Config.java
  src/main/java/goorm/brainsnack/member/domain/Member.java
  src/main/java/goorm/brainsnack/member/dto/MemberResponseDto.java
  src/main/java/goorm/brainsnack/quiz/domain/MemberQuiz.java
  src/main/java/goorm/brainsnack/quiz/domain/SimilarQuiz.java
  src/main/java/goorm/brainsnack/quiz/dto/MemberQuizResponseDto.java
  src/main/java/goorm/brainsnack/quiz/dto/QuizRequestDto.java
  src/main/java/goorm/brainsnack/quiz/dto/QuizResponseDto.java
  src/main/java/goorm/brainsnack/quiz/init/QuizInit.java
  src/main/java/goorm/brainsnack/quiz/init/data-init.xlsx
  src/main/java/goorm/brainsnack/quiz/presentation/QuizController.java
  src/main/java/goorm/brainsnack/quiz/repository/MemberQuizRepository.java
  src/main/java/goorm/brainsnack/quiz/service/QuizServiceImpl.java
Labels: bug, enhancement

#24 Hotfix/quiz num
  gradlew
  src/main/java/goorm/brainsnack/quiz/dto/QuizResponseDto.java
  src/main/java/goorm/brainsnack/quiz/repository/SimilarQuizRepository.java
  src/main/java/goorm/brainsnack/quiz/service/QuizServiceImpl.java
Labels: bug, enhancement
